### ISSUE TITLE
npm run dev

### ISSUE THREAD

**Issue by vikramrojo** [snipcart/vue-prerender-snipcart#2]
Loved the tutorial, being a beginner trying to build a commerce SPA I can't seem to get an npm run dev command working. Could that be added to this repo?

**Comment by vikramrojo** [comment]
Nevermind, I just changed the Public Path to '/' to run "dev": "cross-env NODE_ENV=development webpack-dev-server --open --inline"

**Comment by maximelaboisson** [comment]
Sounds good! :)

Sorry for the delay on this, just saw the notifications. :/
