### ISSUE TITLE
你好,这个针对动态路由要怎么配置啊??

### ISSUE THREAD

**Issue by daolou** [snipcart/vue-prerender-snipcart#4]
### 这种目录的,也就是动态路由: `/myArtical/:id/`,文件名不确定的情况
```
--myArtical
   --0001.html
   --0002.html
        .
        .
        .
```

## 求教

**Comment by youjunzai** [comment]
这个问题你解觉了吗？我也遇到了同样的问题

**Comment by youjunzai** [comment]
> ### 形如:
> ### 这种目录的,也就是动态路由: `/myArtical/:id/`,文件名不确定的情况
> ```
> --myArtical
>    --0001.html
>    --0002.html
>         .
>         .
>         .
> ```
> ### 而且是有很多篇文章,该怎么弄?
> ### 不会是手动一个一个写吧?
> ### 再就是,文章肯定会不定期增加,又该怎么解决啊???
> ## 求教

这个问题解决了吗？？？？

**Comment by daolou** [comment]
> 这个问题你解觉了吗？我也遇到了同样的问题

没有,这个问题太久了,我也早已拥抱react了
